# Generated by Django 5.2.12 on 2026-04-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_normalize_phone_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='affiliation',
            field=models.CharField(blank=True, choices=[('dar_quran', 'دار القرآن'), ('awqaf', 'أوقاف')], default='', max_length=20, verbose_name='التباعية'),
        ),
    ]
