# Generated by Django 5.2.13 on 2026-04-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_failed_login_attempts_user_last_login_attempt_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['full_name'], name='accounts_pa_full_na_34cab9_idx'),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['phone_number'], name='accounts_pa_phone_n_1b5dba_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['full_name'], name='accounts_te_full_na_631c53_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['affiliation'], name='accounts_te_affilia_772e0f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='accounts_us_role_1fa9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='accounts_us_is_acti_a5841d_idx'),
        ),
    ]
