# Generated by Django 5.2.13 on 2026-04-14 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_parent_accounts_pa_full_na_34cab9_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_is_acti_a5841d_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
