# Generated by Django 5.2.13 on 2026-04-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_user_accounts_us_is_acti_a5841d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
    ]
