# Generated by Django 5.2.13 on 2026-04-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_is_active'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(default='', help_text='يُستخدم لتسجيل الدخول', max_length=20, unique=True, verbose_name='رقم الهوية'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='يُستخدم للتواصل والإشعارات', max_length=15, verbose_name='رقم الجوال'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['national_id'], name='accounts_us_nationa_9c8e24_idx'),
        ),
    ]
