# Generated by Django 5.2.13 on 2026-04-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_national_id_set_non_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='sheikh_type',
            field=models.CharField(blank=True, default='', help_text='مثال: شيخ التباعية', max_length=50, verbose_name='نوع الشيخ'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='affiliation',
            field=models.CharField(blank=True, choices=[('dar_quran', 'دار القرآن'), ('awqaf', 'أوقاف'), ('sheikh_tabaea', 'شيخ التباعية')], default='', max_length=20, verbose_name='التباعية'),
        ),
    ]
