# Generated by Django 5.2.12 on 2026-04-15 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_teacher_sheikh_type_alter_teacher_affiliation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='sheikh_type',
        ),
    ]
