# Generated by Django 5.2.12 on 2026-05-04 10:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_remove_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="الاسم الكامل"),
                ),
                (
                    "national_id",
                    models.CharField(
                        help_text="قد يكون هوية حقيقية أو معرف اصطناعي يبدأ بـ 99",
                        max_length=20,
                        unique=True,
                        verbose_name="رقم الهوية",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=15,
                        verbose_name="رقم التواصل",
                    ),
                ),
                (
                    "birthdate",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الميلاد"
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[("single", "أعزب"), ("married", "متزوج")],
                        default="",
                        max_length=10,
                        verbose_name="الحالة الاجتماعية",
                    ),
                ),
                (
                    "education_qualification",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="المؤهل العلمي",
                    ),
                ),
                (
                    "last_tajweed_course",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="آخر دورة تجويد",
                    ),
                ),
                (
                    "family_members_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="عدد أفراد الأسرة"
                    ),
                ),
                (
                    "wallet_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="اسم المحفظة",
                    ),
                ),
                (
                    "wallet_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="رقم المحفظة",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        choices=[
                            ("director", "مدير المركز"),
                            ("deputy_director", "نائب المدير"),
                            ("admin", "الإداري"),
                            ("media", "إعلامي"),
                        ],
                        max_length=30,
                        verbose_name="المسمى الوظيفي",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حساب المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "موظف",
                "verbose_name_plural": "الموظفون",
                "ordering": ["job_title", "full_name"],
                "indexes": [
                    models.Index(
                        fields=["full_name"], name="accounts_st_full_na_94d1af_idx"
                    ),
                    models.Index(
                        fields=["job_title"], name="accounts_st_job_tit_c9cc6c_idx"
                    ),
                ],
            },
        ),
    ]
