# Generated by Django 5.2.12 on 2026-04-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="bank_account_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="اسم الحساب"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="bank_account_number",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="رقم الحساب"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="bank_account_type",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="نوع الحساب"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="desired_courses",
            field=models.TextField(
                blank=True, default="", verbose_name="الدورات المطلوب الالتحاق بها"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="guardian_mobile",
            field=models.CharField(
                default="", max_length=15, verbose_name="رقم جوال ولي الأمر"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="guardian_name",
            field=models.CharField(
                default="", max_length=100, verbose_name="اسم ولي الأمر"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="guardian_national_id",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="رقم هوية ولي الأمر"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="mobile",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="رقم الجوال"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="previous_courses",
            field=models.TextField(
                blank=True, default="", verbose_name="الدورات السابقة"
            ),
        ),
    ]
