# Generated by Django 5.2.13 on 2026-04-10 17:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_failed_login_attempts_user_locked_until'),
        ('students', '0002_student_bank_account_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم الحلقة')),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('inactive', 'متوقفة')], default='active', max_length=20, verbose_name='الحالة')),
                ('level', models.CharField(blank=True, max_length=50, verbose_name='المستوى')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rings', to='accounts.teacher', verbose_name='المحفظ المسؤول')),
            ],
            options={
                'verbose_name': 'حلقة',
                'verbose_name_plural': 'الحلقات',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='ring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.ring', verbose_name='الحلقة'),
        ),
    ]
