# Generated by Django 5.2.12 on 2026-04-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_ring_student_ring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='ring',
        ),
        migrations.AddField(
            model_name='student',
            name='follow_up',
            field=models.TextField(blank=True, default='', verbose_name='التباعية'),
        ),
        migrations.DeleteModel(
            name='Ring',
        ),
    ]
