# Generated by Django 5.2.12 on 2026-04-13 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_add_follow_up_to_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='follow_up',
        ),
    ]
