# Generated by Django 5.2.13 on 2026-04-13 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_parent_accounts_pa_full_na_34cab9_idx_and_more'),
        ('students', '0005_remove_student_follow_up'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['full_name'], name='students_st_full_na_6ea9f7_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['is_active'], name='students_st_is_acti_c00e81_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['enrollment_date'], name='students_st_enrollm_8263f3_idx'),
        ),
    ]
