# Generated by Django 5.2.13 on 2026-04-14 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_students_st_full_na_6ea9f7_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='student',
            name='students_st_is_acti_c00e81_idx',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
    ]
