# Generated by Django 5.2.13 on 2026-04-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_student_students_st_is_acti_c00e81_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='affiliation',
            field=models.CharField(blank=True, choices=[('dar_quran', 'دار القرآن'), ('awqaf', 'أوقاف')], default='', max_length=20, verbose_name='التباعية'),
        ),
    ]
