# Generated by Django 5.2.13 on 2026-04-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_remove_student_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='review_interval_days',
            field=models.PositiveIntegerField(default=14, verbose_name='فترة دوران المراجعة (أيام)'),
        ),
    ]
