# Generated by Django 5.2.12 on 2026-04-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_student_review_interval_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='national_id',
        ),
    ]
