# Generated by Django 5.2.12 on 2026-05-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0013_student_quran_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="current_aya",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="الآية الحالية"
            ),
        ),
    ]
