# Generated by Django 5.2.12 on 2026-05-11 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0014_add_student_current_aya"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="current_aya",
            new_name="current_page",
        ),
    ]
