# Generated by Django 5.2.12 on 2026-05-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0015_rename_current_aya_to_current_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="current_page",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="الصفحة الحالية"
            ),
        ),
    ]
