# Generated by Django 5.2.16 on 2026-07-14 14:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0016_alter_student_current_page"),
        ("teacher", "0003_alter_teacher_job_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentChangeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("assign", "ضم لحلقتي"),
                            ("unassign", "إزالة من حلقتي"),
                            ("create", "تسجيل طالب جديد"),
                            ("update", "تعديل بيانات"),
                            ("delete", "حذف الطالب"),
                        ],
                        max_length=20,
                        verbose_name="الإجراء",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("approved", "موافَق عليه"),
                            ("rejected", "مرفوض"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="البيانات المقترحة"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ المراجعة"
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, default="", verbose_name="ملاحظة"),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_change_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مقدّم الطلب",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_change_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="راجعه",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_requests",
                        to="students.student",
                        verbose_name="الطالب",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests",
                        to="teacher.teacher",
                        verbose_name="المحفظ",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب تعديل طالب",
                "verbose_name_plural": "طلبات تعديل الطلاب",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["teacher", "status"],
                        name="students_st_teacher_32e251_idx",
                    )
                ],
            },
        ),
    ]
