# Generated by Django 5.2.15 on 2026-07-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0017_studentchangerequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="memorized_verses",
            field=models.PositiveIntegerField(default=0, verbose_name="عدد الصفحات"),
        ),
    ]
