# Generated by Django 6.0.6 on 2026-08-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_alter_student_memorized_verses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='memorized_verses',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الآيات'),
        ),
    ]
