# Generated by Django 5.2.13 on 2026-04-13 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_dailyrecord_result'),
        ('students', '0006_student_students_st_full_na_6ea9f7_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailyrecord',
            index=models.Index(fields=['date'], name='records_dai_date_8e04a3_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyrecord',
            index=models.Index(fields=['attendance'], name='records_dai_attenda_16fdd5_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyrecord',
            index=models.Index(fields=['quality'], name='records_dai_quality_9a05c1_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyrecord',
            index=models.Index(fields=['result'], name='records_dai_result_3a663d_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyplan',
            index=models.Index(fields=['week_start'], name='records_wee_week_st_2befc7_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyplan',
            index=models.Index(fields=['week_number'], name='records_wee_week_nu_5fd105_idx'),
        ),
    ]
