# Generated by Django 5.2.13 on 2026-04-20 17:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_dailyrecord_records_dai_date_8e04a3_idx_and_more'),
        ('students', '0010_student_review_interval_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('surah_name', models.CharField(max_length=100, verbose_name='اسم السورة')),
                ('reviewed_date', models.DateField(verbose_name='تاريخ المراجعة')),
                ('quality', models.CharField(choices=[('excellent', 'ممتاز'), ('good', 'جيد جداً'), ('acceptable', 'جيد'), ('weak', 'ضعيف'), ('none', 'لم يُسمّع')], default='none', max_length=10, verbose_name='جودة المراجعة')),
                ('note', models.TextField(blank=True, default='', verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_reviews', to=settings.AUTH_USER_MODEL, verbose_name='المسجّل')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_records', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'سجل مراجعة',
                'verbose_name_plural': 'سجلات المراجعة',
                'ordering': ['-reviewed_date'],
                'indexes': [models.Index(fields=['student', 'reviewed_date'], name='records_rev_student_6a637a_idx'), models.Index(fields=['student', 'surah_name'], name='records_rev_student_57f936_idx')],
                'unique_together': {('student', 'surah_name', 'reviewed_date')},
            },
        ),
    ]
