# Generated by Django 5.2.15 on 2026-07-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0006_surah_mastery"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyrecord",
            name="review_from_ayah",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="مراجعة من آية"
            ),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="review_quality",
            field=models.CharField(
                choices=[
                    ("excellent", "ممتاز"),
                    ("good", "جيد جداً"),
                    ("acceptable", "جيد"),
                    ("weak", "ضعيف"),
                    ("none", "لم يُسمّع"),
                ],
                default="none",
                max_length=10,
                verbose_name="جودة المراجعة",
            ),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="review_surah_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="اسم سورة المراجعة"
            ),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="review_to_ayah",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="مراجعة إلى آية"
            ),
        ),
        migrations.AlterField(
            model_name="dailyrecord",
            name="achieved_verses",
            field=models.PositiveIntegerField(
                default=0, verbose_name="الصفحات المنجزة"
            ),
        ),
        migrations.AlterField(
            model_name="dailyrecord",
            name="required_verses",
            field=models.PositiveIntegerField(
                default=0, verbose_name="الصفحات المطلوبة"
            ),
        ),
        migrations.AlterField(
            model_name="weeklyplan",
            name="total_achieved",
            field=models.PositiveIntegerField(
                default=0, verbose_name="إجمالي الصفحات المنجزة"
            ),
        ),
        migrations.AlterField(
            model_name="weeklyplan",
            name="total_required",
            field=models.PositiveIntegerField(
                default=0, verbose_name="إجمالي الصفحات المطلوبة"
            ),
        ),
    ]
