# Generated by Django 6.0.6 on 2026-07-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_dailyrecord_review_from_ayah_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='next_memorization_target',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='المطلوب تسميعه غداً (حفظ)'),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='next_review_target',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='المطلوب تسميعه غداً (مراجعة)'),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='achieved_verses',
            field=models.PositiveIntegerField(default=0, verbose_name='الآيات المنجزة'),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='required_verses',
            field=models.PositiveIntegerField(default=0, verbose_name='الآيات المطلوبة'),
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='total_achieved',
            field=models.PositiveIntegerField(default=0, verbose_name='إجمالي الآيات المنجزة'),
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='total_required',
            field=models.PositiveIntegerField(default=0, verbose_name='إجمالي الآيات المطلوبة'),
        ),
    ]
