# Generated by Django 6.0.6 on 2026-07-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_dailyrecord_next_memorization_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='next_memorization_from_ayah',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حفظ غداً من آية'),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='next_memorization_to_ayah',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حفظ غداً إلى آية'),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='next_review_from_ayah',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مراجعة غداً من آية'),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='next_review_to_ayah',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مراجعة غداً إلى آية'),
        ),
    ]
