# Generated by Django 6.0.6 on 2026-08-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_dailyrecord_next_memorization_from_ayah_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='from_ayah',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='من آية'),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='memorized_lines',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الأسطر المحفوظة'),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='to_ayah',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='إلى آية'),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='total_lines',
            field=models.PositiveIntegerField(default=0, verbose_name='إجمالي الأسطر المحفوظة'),
        ),
    ]
