# Generated by Django 6.0.6 on 2026-08-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_dailyrecord_from_ayah_dailyrecord_memorized_lines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyplan',
            name='total_required_lines',
            field=models.PositiveIntegerField(default=0, verbose_name='إجمالي الأسطر المطلوبة'),
        ),
    ]
