# Generated by Django 6.0.6 on 2026-08-11 05:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_dailyrecord_student'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dailyrecord',
            new_name='records_dai_student_3fe806_idx',
            old_name='records_dai_student_447ff4_idx',
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='required_pages',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='عدد الصفحات المطلوبة'),
        ),
    ]
