# Generated by Django on 2026-08-11

from decimal import Decimal
from django.db import migrations

def backfill_required_pages(apps, schema_editor):
    WeeklyPlan = apps.get_model('records', 'WeeklyPlan')
    for plan in WeeklyPlan.objects.all():
        if plan.total_required_lines > 0:
            plan.required_pages = Decimal(str(round(plan.total_required_lines / 15, 2)))
            plan.save(update_fields=['required_pages'])

def reverse_backfill(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_rename_records_dai_student_447ff4_idx_records_dai_student_3fe806_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_required_pages, reverse_backfill),
    ]
