# Generated by Django 5.2.17 on 2026-08-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_backfill_required_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='morals_rating',
            field=models.CharField(choices=[('excellent', 'ممتاز'), ('good', 'جيد'), ('acceptable', 'مقبول'), ('weak', 'يحتاج متابعة'), ('none', 'غير مقيم')], default='none', max_length=20, verbose_name='تقييم الأخلاق'),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='review_from_page',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مراجعة من صفحة'),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='review_to_page',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مراجعة إلى صفحة'),
        ),
    ]
