# Generated by Django 5.2.17 on 2026-08-12 13:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_dailyrecord_morals_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyplan',
            name='review_required_pages',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='عدد صفحات المراجعة المطلوبة'),
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='required_pages',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='عدد صفحات الحفظ المطلوبة'),
        ),
    ]
