# Generated by Django 5.2.17 on 2026-08-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0019_dailyrecord_test_scores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyplan',
            options={'ordering': ['-week_start'], 'verbose_name': 'خطة حفظ', 'verbose_name_plural': 'خطط الحفظ'},
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='month_start',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='بداية الشهر'),
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='week_number',
            field=models.PositiveIntegerField(default=0, verbose_name='رقم الأسبوع'),
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='week_start',
            field=models.DateField(verbose_name='بداية الفترة'),
        ),
    ]
