# Generated by Django 5.2.16 on 2026-07-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification_notificatio_recipie_a972ce_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("absence", "غياب"),
                    ("announcement", "إعلان"),
                    ("reminder", "تذكير"),
                    ("report", "تقرير"),
                    ("teacher_request", "طلب محفظ"),
                ],
                max_length=20,
                verbose_name="نوع الإشعار",
            ),
        ),
    ]
