# Generated by Django 6.0.6 on 2026-08-08 21:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_type'),
        ('students', '0019_alter_student_memorized_verses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('absence', 'غياب'), ('announcement', 'إعلان'), ('reminder', 'تذكير'), ('report', 'تقرير'), ('teacher_request', 'طلب محفظ'), ('direct_message', 'رسالة مباشرة')], max_length=20, verbose_name='نوع الإشعار'),
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_role', models.CharField(choices=[('teacher', 'محفظ'), ('student', 'طالب'), ('admin', 'مدير')], max_length=10, verbose_name='دور المرسل')),
                ('body', models.TextField(verbose_name='نص الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_direct_messages', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_messages', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'رسالة مباشرة',
                'verbose_name_plural': 'الرسائل المباشرة',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['student', 'created_at'], name='notificatio_student_d5b597_idx'), models.Index(fields=['sender', '-created_at'], name='notificatio_sender__1d9fa2_idx')],
            },
        ),
    ]
