# Generated by Django 5.2.12 on 2026-04-04 11:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="الاسم الرباعي"),
                ),
                (
                    "national_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="رقم الهوية"
                    ),
                ),
                ("birthdate", models.DateField(verbose_name="تاريخ الميلاد")),
                ("grade", models.CharField(max_length=50, verbose_name="الصف الدراسي")),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="عنوان السكن"),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="رقم واتساب"
                    ),
                ),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("normal", "طبيعي"),
                            ("martyr_son", "ابن شهيد"),
                            ("injured", "جريح"),
                            ("sick", "مريض"),
                            ("other", "أخرى"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="الحالة الصحية",
                    ),
                ),
                (
                    "health_note",
                    models.TextField(blank=True, verbose_name="تفاصيل الحالة الصحية"),
                ),
                (
                    "skills",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"quran": true, "nasheed": false, "poetry": false, "other": false}',
                        verbose_name="المهارات",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="students/photos/",
                        verbose_name="صورة الطالب",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "enrollment_date",
                    models.DateField(auto_now_add=True, verbose_name="تاريخ الالتحاق"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="accounts.teacher",
                        verbose_name="المحفظ المسؤول",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حساب المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "طالب",
                "verbose_name_plural": "الطلاب",
                "ordering": ["full_name"],
            },
        ),
    ]
