# Generated by Django 5.2.13 on 2026-04-20 17:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0010_student_review_interval_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الاختبار')),
                ('surah_range', models.CharField(blank=True, default='', max_length=200, verbose_name='نطاق السور')),
                ('scheduled_date', models.DateField(verbose_name='تاريخ الاختبار')),
                ('status', models.CharField(choices=[('scheduled', 'مجدول'), ('passed', 'ناجح'), ('failed', 'راسب'), ('missed', 'متغيّب')], default='scheduled', max_length=12, verbose_name='الحالة')),
                ('result_note', models.TextField(blank=True, default='', verbose_name='ملاحظة النتيجة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'اختبار',
                'verbose_name_plural': 'الاختبارات',
                'ordering': ['scheduled_date'],
                'indexes': [models.Index(fields=['student', 'scheduled_date'], name='evaluations_student_c7e366_idx'), models.Index(fields=['status'], name='evaluations_status_f07c59_idx')],
            },
        ),
    ]
