# Generated by Django 5.2.12 on 2026-04-24 14:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
        ('students', '0012_alter_student_teacher_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='بدأ في')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='سُلِّم في')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الدرجة')),
                ('answers', models.JSONField(blank=True, default=dict, verbose_name='الإجابات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='evaluations.evaluation', verbose_name='الاختبار')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'محاولة اختبار',
                'verbose_name_plural': 'محاولات الاختبارات',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['evaluation', 'student'], name='evaluations_evaluat_83a791_idx'), models.Index(fields=['student', 'started_at'], name='evaluations_student_a92f17_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('prompt', models.TextField(verbose_name='نص السؤال')),
                ('question_type', models.CharField(choices=[('mcq', 'اختيار من متعدد'), ('fill_blank', 'إكمال فراغ'), ('verse_continuation', 'إكمال آية')], default='mcq', max_length=20, verbose_name='نوع السؤال')),
                ('options', models.JSONField(blank=True, default=list, help_text='لأسئلة الاختيار من متعدد فقط.', verbose_name='الخيارات')),
                ('correct_answer', models.TextField(verbose_name='الإجابة الصحيحة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='evaluations.evaluation', verbose_name='الاختبار')),
            ],
            options={
                'verbose_name': 'سؤال اختبار',
                'verbose_name_plural': 'أسئلة الاختبارات',
                'ordering': ['evaluation', 'order'],
                'indexes': [models.Index(fields=['evaluation', 'order'], name='evaluations_evaluat_0eb355_idx')],
            },
        ),
    ]
