# Generated by Django 5.2.12 on 2026-05-11 11:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0016_alter_student_current_page"),
        ("teacher", "0003_alter_teacher_job_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "surah_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(114),
                        ],
                        verbose_name="رقم السورة",
                    ),
                ),
                (
                    "surah_name",
                    models.CharField(
                        help_text="يُملأ تلقائياً من رقم السورة",
                        max_length=50,
                        verbose_name="اسم السورة",
                    ),
                ),
                (
                    "juz_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                        verbose_name="رقم الجزء",
                    ),
                ),
                (
                    "from_page",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="من صفحة"
                    ),
                ),
                (
                    "to_page",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="إلى صفحة"
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, default="", verbose_name="ملاحظة"),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التسجيل"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_entries",
                        to="students.student",
                        verbose_name="الطالب",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_progress",
                        to="teacher.teacher",
                        verbose_name="المحفظ المسجّل",
                    ),
                ),
            ],
            options={
                "verbose_name": "تقدم حفظ",
                "verbose_name_plural": "سجل تقدم الحفظ",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "-recorded_at"],
                        name="progress_st_student_255bd0_idx",
                    ),
                    models.Index(
                        fields=["student", "surah_number"],
                        name="progress_st_student_cc7e26_idx",
                    ),
                ],
            },
        ),
    ]
