# Generated by Django 5.2.15 on 2026-07-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprogress",
            name="from_page",
        ),
        migrations.RemoveField(
            model_name="studentprogress",
            name="to_page",
        ),
        migrations.AddField(
            model_name="studentprogress",
            name="from_ayah",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="من آية"
            ),
        ),
        migrations.AddField(
            model_name="studentprogress",
            name="to_ayah",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="إلى آية"
            ),
        ),
        migrations.AddField(
            model_name="studentprogress",
            name="type",
            field=models.CharField(
                choices=[("memorization", "memorization"), ("revision", "revision")],
                default="memorization",
                max_length=20,
                verbose_name="نوع التقدم",
            ),
        ),
    ]
