# Generated by Django 5.2.13 on 2026-04-20 18:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('op_id', models.UUIDField(primary_key=True, serialize=False, verbose_name='معرّف العملية')),
                ('resource', models.CharField(max_length=32, verbose_name='النوع')),
                ('action', models.CharField(max_length=16, verbose_name='الإجراء')),
                ('status', models.CharField(max_length=16, verbose_name='الحالة')),
                ('result_json', models.JSONField(verbose_name='نتيجة محفوظة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مفتاح منع التكرار',
                'verbose_name_plural': 'مفاتيح منع التكرار',
                'indexes': [models.Index(fields=['user', 'created_at'], name='sync_idempo_user_id_eeeb87_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tombstone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource', models.CharField(choices=[('student', 'طالب'), ('teacher', 'محفظ'), ('parent', 'ولي أمر'), ('parent_student_link', 'ربط ولي أمر بطالب'), ('weekly_plan', 'خطة أسبوعية'), ('daily_record', 'سجل يومي'), ('review_record', 'سجل مراجعة'), ('evaluation', 'اختبار'), ('notification', 'إشعار'), ('course', 'دورة'), ('student_course', 'تسجيل طالب بدورة')], max_length=32, verbose_name='النوع')),
                ('resource_uuid', models.UUIDField(verbose_name='معرّف السجل المحذوف')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحذف')),
                ('scope_user_id', models.UUIDField(blank=True, null=True, verbose_name='نطاق الرؤية')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='من قام بالحذف')),
            ],
            options={
                'verbose_name': 'شاهدة حذف',
                'verbose_name_plural': 'شواهد الحذف',
                'ordering': ['-deleted_at'],
                'indexes': [models.Index(fields=['resource', 'deleted_at'], name='sync_tombst_resourc_855ab0_idx'), models.Index(fields=['deleted_at'], name='sync_tombst_deleted_a4ccdc_idx')],
            },
        ),
    ]
