# Generated by Django 5.2.12 on 2026-05-06 12:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "generation_id",
                    models.UUIDField(
                        default=uuid.uuid4, verbose_name="معرّف الجيل الحالي للمزامنة"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
            ],
            options={
                "verbose_name": "جيل المزامنة",
                "verbose_name_plural": "أجيال المزامنة",
            },
        ),
    ]
