# Generated by Django 5.2.15 on 2026-07-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0002_syncgeneration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tombstone",
            name="resource",
            field=models.CharField(
                choices=[
                    ("student", "طالب"),
                    ("teacher", "محفظ"),
                    ("parent", "ولي أمر"),
                    ("parent_student_link", "ربط ولي أمر بطالب"),
                    ("weekly_plan", "خطة أسبوعية"),
                    ("daily_record", "سجل يومي"),
                    ("review_record", "سجل مراجعة"),
                    ("evaluation", "اختبار"),
                    ("notification", "إشعار"),
                    ("course", "دورة"),
                    ("student_course", "تسجيل طالب بدورة"),
                    ("progress", "تقدم الحفظ"),
                ],
                max_length=32,
                verbose_name="النوع",
            ),
        ),
    ]
