# Generated by Django 5.2.12 on 2026-04-04 11:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "week_number",
                    models.PositiveIntegerField(verbose_name="رقم الأسبوع"),
                ),
                ("week_start", models.DateField(verbose_name="بداية الأسبوع (السبت)")),
                (
                    "total_required",
                    models.PositiveIntegerField(
                        default=0, verbose_name="إجمالي الآيات المطلوبة"
                    ),
                ),
                (
                    "total_achieved",
                    models.PositiveIntegerField(
                        default=0, verbose_name="إجمالي الآيات المنجزة"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_plans",
                        to="students.student",
                        verbose_name="الطالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "خطة أسبوعية",
                "verbose_name_plural": "الخطط الأسبوعية",
                "ordering": ["-week_start"],
                "unique_together": {("student", "week_start")},
            },
        ),
        migrations.CreateModel(
            name="DailyRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("sat", "السبت"),
                            ("sun", "الأحد"),
                            ("mon", "الاثنين"),
                            ("tue", "الثلاثاء"),
                            ("wed", "الأربعاء"),
                            ("thu", "الخميس"),
                        ],
                        max_length=3,
                        verbose_name="اليوم",
                    ),
                ),
                ("date", models.DateField(verbose_name="التاريخ")),
                (
                    "attendance",
                    models.CharField(
                        choices=[
                            ("present", "حاضر"),
                            ("absent", "غائب"),
                            ("late", "متأخر"),
                            ("excused", "مستأذن"),
                        ],
                        default="present",
                        max_length=10,
                        verbose_name="الحضور",
                    ),
                ),
                (
                    "required_verses",
                    models.PositiveIntegerField(
                        default=0, verbose_name="الآيات المطلوبة"
                    ),
                ),
                (
                    "achieved_verses",
                    models.PositiveIntegerField(
                        default=0, verbose_name="الآيات المنجزة"
                    ),
                ),
                (
                    "surah_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="اسم السورة"
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("excellent", "ممتاز"),
                            ("good", "جيد جداً"),
                            ("acceptable", "جيد"),
                            ("weak", "ضعيف"),
                            ("none", "لم يُسمّع"),
                        ],
                        default="none",
                        max_length=10,
                        verbose_name="جودة الحفظ",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="ملاحظة المحفظ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المسجّل",
                    ),
                ),
                (
                    "weekly_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_records",
                        to="records.weeklyplan",
                        verbose_name="الخطة الأسبوعية",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل يومي",
                "verbose_name_plural": "السجلات اليومية",
                "ordering": ["date"],
                "unique_together": {("weekly_plan", "day")},
            },
        ),
    ]
