# Generated by Django 5.2.12 on 2026-05-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="birthdate",
            field=models.DateField(blank=True, null=True, verbose_name="تاريخ الميلاد"),
        ),
        migrations.AddField(
            model_name="teacher",
            name="education_qualification",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="المؤهل العلمي"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="family_members_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="عدد أفراد الأسرة"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="job_title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("teacher", "محفظ"),
                    ("teacher_reception", "محفظ استقبال"),
                    ("teacher_year_circle", "محفظ حلقة سنة"),
                    ("teacher_forum_circle", "محفظ حلقة منتدى"),
                    ("teacher_assistant", "مساعد محفظ"),
                    ("course_instructor", "معلم دورات"),
                    ("admin_teacher", "مساعد إداري + محفظ"),
                ],
                default="teacher",
                max_length=30,
                verbose_name="المسمى الوظيفي",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="last_tajweed_course",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="آخر دورة تجويد"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[("single", "أعزب"), ("married", "متزوج")],
                default="",
                max_length=10,
                verbose_name="الحالة الاجتماعية",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="wallet_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="اسم المحفظة"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="wallet_number",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="رقم المحفظة"
            ),
        ),
    ]
