# Generated by Django 5.2.12 on 2026-05-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0002_teacher_birthdate_teacher_education_qualification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="job_title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("teacher", "محفظ"),
                    ("teacher_reception", "محفظ استقبال"),
                    ("teacher_year_circle", "محفظ حلقة سنة"),
                    ("teacher_forum_circle", "محفظ حلقة منتدى"),
                    ("teacher_assistant", "مساعد محفظ"),
                    ("course_instructor", "معلم دورات"),
                    ("admin_teacher", "مساعد إداري + محفظ"),
                    ("director", "مدير المركز"),
                    ("deputy_director", "نائب المدير"),
                    ("admin", "إداري"),
                    ("media", "إعلامي"),
                ],
                default="teacher",
                max_length=30,
                verbose_name="المسمى الوظيفي",
            ),
        ),
    ]
